[package]
name = "xffs-tools"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[lints]
workspace = true

[dependencies]
xffs-core = { path = "../xffs-core" }
clap = { version = "=4.5.48", features = ["derive"] }
uuid = "=1.18.1"
crc32c = "=0.6.8"

[[bin]]
name = "mkfs-xffs"
path = "src/bin/mkfs.rs"

[dev-dependencies]
xffs-sim = { path = "../xffs-sim" }
